driver:
  name: terraform
  variable_files:
    - terraform-testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: aws

verifier:
  name: awspec

suites:
  - name: default
    verifier:
      patterns:
      - test/integration/default/*_spec.rb
