source 'https://rubygems.org'
gem 'aws-sdk', '3.0.1'
gem 'awsecrets', '1.14.0'
gem 'awspec', '1.5.2'
gem 'kitchen-terraform', '3.3.0'
gem 'kitchen-verifier-awspec', '0.1.1'
gem 'test-kitchen', '1.21.1'
